//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guoli.Fs.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartFiles
    {
    	    public int Id { get; set; }
    	    public string FileName { get; set; }
    	    public int FileInfoId { get; set; }
    	    public int FileDirectoryId { get; set; }
    	    public int SystemUserId { get; set; }
    	    public System.DateTime LastModifyTime { get; set; }
    	    public bool IsDeleted { get; set; }
    	    public int DepartmentId { get; set; }
    	    public bool IsCommon { get; set; }
    }
}
