//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guoli.Fs.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BtsEntities : DbContext
    {
        public BtsEntities()
            : base("name=BtsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DepartFiles> DepartFiles { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<FileDirectory> FileDirectory { get; set; }
        public virtual DbSet<FileInfo> FileInfo { get; set; }
        public virtual DbSet<PersonInfo> PersonInfo { get; set; }
        public virtual DbSet<SystemDict> SystemDict { get; set; }
        public virtual DbSet<SystemLog> SystemLog { get; set; }
        public virtual DbSet<SystemUser> SystemUser { get; set; }
        public virtual DbSet<ViewPersonInfo> ViewPersonInfo { get; set; }
        public virtual DbSet<ViewSystemUser> ViewSystemUser { get; set; }
        public virtual DbSet<OperationLog> OperationLog { get; set; }
        public virtual DbSet<ViewDepartFiles> ViewDepartFiles { get; set; }
        public virtual DbSet<DbUpdateLog> DbUpdateLog { get; set; }
    }
}
