//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guoli.Fs.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewPersonInfo
    {
    	    public int Id { get; set; }
    	    public string Name { get; set; }
    	    public int Gender { get; set; }
    	    public string HeadPortraitPath { get; set; }
    	    public int DepartmentId { get; set; }
    	    public System.DateTime AddTime { get; set; }
    	    public bool IsDeleted { get; set; }
    	    public string DepartmentName { get; set; }
    	    public Nullable<int> ParentDepartmentId { get; set; }
    	    public string WorkNo { get; set; }
    	    public string Username { get; set; }
    	    public Nullable<int> UserType { get; set; }
    	    public string Password { get; set; }
    }
}
